### ISSUE TITLE
`tox.toml` is hidden in a subdir

### ISSUE THREAD

**Issue by mtelka** [tox-dev/toml-fmt#11]
The `pyproject_fmt-2.4.3` sdist contains `tox.toml` hidden in the `pyproject-fmt` sub-directory and so `tox` fails unexpectedly in the top level directory:

```
$ wget https://files.pythonhosted.org/packages/source/p/pyproject_fmt/pyproject_fmt-2.4.3.tar.gz
$ gtar xf pyproject_fmt-2.4.3.tar.gz
$ cd pyproject_fmt-2.4.3
$ tox -l
ROOT: No tox.ini or setup.cfg or pyproject.toml or tox.toml found, assuming empty tox.ini at /tmp/test/pyproject_fmt-2.4.3
$
```

**Comment by gaborbernat** [comment]
This is expected. This project moved into a monorepo and accordingly, you are expected to run the commands for `pyproject-fmt` from within that folder.

**Comment by mtelka** [comment]
Shouldn't be the `pyproject.toml` file located in the `pyproject-fmt` subdir too?

Thank you.

**Comment by gaborbernat** [comment]
There's one both. The root is just holding the ruff config.
